services:
  - type: web
    name: doctor-search-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install
    startCommand: chmod +x run_render.sh && ./run_render.sh
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: BACKEND_API_URL
        value: http://localhost:8000
      - key: FRONTEND_URL
        fromService:
          name: doctor-search-app
          type: web
          property: url
      - key: PORT
        value: 8000
      - key: NODE_VERSION
        value: 18
      - key: PYTHON_VERSION
        value: 3.11.7
    healthCheckPath: /
    autoDeploy: true
    plan: starter 