services:
  - type: web
    name: doctor-search-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install
    startCommand: chmod +x run_render.sh && ./run_render.sh
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: BACKEND_API_URL
        value: http://localhost:8000
      - key: FRONTEND_URL
        value: http://localhost:3000
      - key: PORT
        value: 3000
      - key: NODE_VERSION
        value: 18
    healthCheckPath: /health
    autoDeploy: true
    plan: starter 