services:
  - type: web
    name: doctor-search-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://doctor-search-frontend.onrender.com
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: doctor-search-frontend
    env: python
    buildCommand: cd streamlit-frontend && pip install -r requirements.txt
    startCommand: cd streamlit-frontend && streamlit run app_streamlit.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: BACKEND_API_URL
        value: https://doctor-search-backend.onrender.com
    healthCheckPath: /
    autoDeploy: true 