services:
  - type: web
    name: doctor-search-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd streamlit-frontend && pip install -r requirements.txt
    startCommand: chmod +x run_render.sh && ./run_render.sh
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: BACKEND_API_URL
        value: http://localhost:8000
      - key: FRONTEND_URL
        value: http://localhost:8000
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true 